clubweb/clubweb/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    #Urls Django
    path('admin/', admin.site.urls),
    #Extras
    url(r'^tinymce/', include('tinymce.urls')),
    #Apps Propias
    path('', include('core.urls', namespace='core_app')),
    path('georef/', include('georef.urls')),
    path('calendario/', include('calendario.urls')),
    path('noticias/', include('noticias.urls')),
    path('socios/', include('socios.urls')),
    path('comercio/', include('comercio.urls')),
    path('organigrama/', include('organigrama.urls')),
    path('personal/', include('personal.urls')),
    path('finanzas/', include('finanzas.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clubweb/core/urls.py
from django.conf.urls import url
from django.urls import path
#Import personales
from . import views

app_name = 'core'
urlpatterns = [
    #Basicas:
    url(r'^$', views.home, name='home'),
    path('faq/', views.faqs, name='faqs'),
    path('contacto/', views.contacto, name='contacto'),
    
    #Web Services
    path('ws/', views.ws_core, name='ws_core'),
    path('ws/<str:nombre_app>/<str:nombre_modelo>/', views.ws_core, name='ws_core'),

    #Task Manager:
    #path('task_progress/<str:queue_name>', tasks.task_progress, name='task_progress'),
]

clubweb/personal/urls.py
#Imports Django
from django.urls import path
from django.conf.urls import url
#Import personales
from . import views

app_name = 'personal'
urlpatterns = [
    #Basicas:
    path('', views.personal_menu, name='personal_menu'),

    #Menu:
    path('buscar', views.resumen_empleado, name='resumen_empleado'),
    path('buscarhabilidades', views.buscar_por_habilidad, name='buscar_por_habilidad'),
    path('turnos', views.ver_turnos, name='ver_turnos'),
    path('postulantes', views.ver_postulantes, name='ver_postulantes'),
    #Busquedas
    path('buscar/<int:id_empleado>', views.resumen_empleado, name='resumen_empleado'),
    path('turnos/<int:id_sector>', views.ver_turnos, name='ver_turnos'),
    path('buscador', views.buscador, name='buscador'),
    #Salarios
    url(r'salarios/(?P<fecha>\d{4}-\d{2}-\d{2})/$', views.ver_salarios, name='ver_salarios'),
    path('upload_salarios', views.upload_salarios, name='upload_salarios'),
    path('excel_ejemplo_simple', views.excel_ejemplo_simple, name='excel_ejemplo_simple'),
    path('excel_ejemplo_avanzado', views.excel_ejemplo_avanzado, name='excel_ejemplo_avanzado'),
]

clubweb/socios/models.py
#Imports de python
from datetime import datetime
#Import de Django
from django.db import models
from django.contrib.auth.models import User
#Imports Extras
from tinymce.models import HTMLField
#Imports del proyecto
from georef.models import Localidad, Barrio
#Imports de la app
from .choices import TIPO_DOCUMENTOS, ESTADO_CIVIL, TIPO_EVENTO_SOCIO

# Create your models here.
class TipoSocio(models.Model):
    orden = models.SmallIntegerField(unique=True)
    nombre = models.CharField(verbose_name="Tipo de Socio", max_length=50)
    precio = models.DecimalField(verbose_name="Precio Mensual", max_digits=8, decimal_places=2)
    def __str__(self):
        return self.nombre

class TipoAlojamiento(models.Model):
    orden = models.SmallIntegerField(unique=True)
    nombre = models.CharField(verbose_name="Tipo de Alojamiento", max_length=50)
    precio = models.DecimalField(verbose_name="Precio Mensual", max_digits=8, decimal_places=2)
    def __str__(self):
        return self.nombre

class TipoPago(models.Model):
    nombre = models.CharField(verbose_name="Tipo de Pago", max_length=50)
    descripcion = HTMLField(blank=True, null=True)
    def __str__(self):
        return self.nombre

class Socio(models.Model):
    tipo_socio = models.ForeignKey(TipoSocio, on_delete=models.SET_NULL, related_name="socios", blank=True, null=True)
    num_socio = models.IntegerField(unique=True, null=True, blank=True)
    tipo_doc = models.IntegerField(choices=TIPO_DOCUMENTOS, default=2)
    num_doc = models.IntegerField('Num de Documento', unique=True, null=True, blank=True)
    apellidos = models.CharField('Apellidos', max_length=100)
    nombres = models.CharField('Nombres', max_length=100)
    fecha_nacimiento = models.DateField(verbose_name="Fecha de Nacimiento", null=True, blank=True)
    estado_civil = models.IntegerField(choices=ESTADO_CIVIL, default=2)
    email = models.EmailField('Correo Electronico', null=True, blank=True)
    fotografia = models.FileField('Fotografia', upload_to='socios/foto/', default='/static/img/noimage.png', blank=True, null=True)
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="socios")
    #Campos dinamicos
    def _estado(self):
        try:
            return self.eventos.order_by('fecha').last().tipo
        except self.DoesNotExist:
            return 'SE'
    estado = property(_estado)
    #Propiedades
    class Meta:
        ordering = ['num_socio']
   
    def __str__(self):
        return self.apellidos + ', ' + self.nombres

class EventoSocio(models.Model):
    socio = models.ForeignKey(Socio, on_delete=models.SET_NULL, null=True, related_name="eventos")
    tipo = models.CharField(max_length=2, choices=TIPO_EVENTO_SOCIO, default='SE')
    fecha = models.DateTimeField(verbose_name="Fecha del Evento", default=datetime.now)
    descripcion = models.CharField(max_length=200, blank=True, null=True)
    class Meta:
        ordering = ['fecha']
    def __str__(self):
        return str(self.socio) + ': ' + self.get_tipo_display() + ' el ' + str(self.fecha)
    def as_dict(self):
        return {
            "socio_id": self.socio.id,
            "tipo_evento": self.get_tipo_evento_display(),
            "fecha": str(self.fecha),
        }

class Domicilio(models.Model):
    socio = models.ForeignKey(Socio, on_delete=models.SET_NULL, null=True, related_name="domicilios_socio")
    localidad = models.ForeignKey(Localidad, on_delete=models.SET_NULL, related_name="domicilios_socio", blank=True, null=True)
    barrio = models.ForeignKey(Barrio, on_delete=models.SET_NULL, related_name="domicilios_socio", blank=True, null=True)
    calle = models.CharField('Calle', max_length=50, blank=True, null=True)
    numero = models.CharField('Numero', max_length=50, blank=True, null=True)

class Telefono(models.Model):
    socio = models.ForeignKey(Socio, on_delete=models.CASCADE, related_name="telefonos_socio")
    prefijo = models.CharField('Prefijo', max_length=5, blank=True, null=True, default="+54")
    cod_area = models.CharField('Codigo de Area', max_length=5, blank=True, null=True, default="342")
    telefono = models.CharField('Telefono', max_length=10, blank=True, null=True)
    def __str__(self):
        return self.prefijo + self.cod_area + self.telefono

class Embarcacion(models.Model):
    socio = models.ForeignKey(Socio, on_delete=models.CASCADE, related_name="embarcaciones")
    tipo_alojamiento = models.ForeignKey(TipoAlojamiento, on_delete=models.CASCADE, related_name="embarcaciones")
    casco_marca = models.CharField('Marca', max_length=20)
    casco_modelo = models.CharField('Modelo', max_length=50)
    casco_nombre = models.CharField('Nombre', max_length=50, blank=True, null=True)
    casco_matricula = models.CharField('Matricula', max_length=10, blank=True, null=True)
    motor_marca = models.CharField('Marca', max_length=20, blank=True, null=True)
    motor_modelo = models.CharField('Modelo', max_length=20, blank=True, null=True)
    motor_potencia = models.CharField('Potencia', max_length=10, blank=True, null=True)
    alojada = models.BooleanField(verbose_name="Alojada Actualmente", default=True)
    class Meta:
        verbose_name_plural = 'Embarcaciones'
    def __str__(self):
        return self.casco_marca + ' ' + self.casco_modelo + ' de ' + str(self.socio) + ' (' + (self.tipo_alojamiento.nombre) + ')'

#Pagos
class Cuota(models.Model):
    socio = models.ForeignKey(Socio, on_delete=models.CASCADE, related_name="cuotas")
    ano_cuota = models.IntegerField('Año', choices=[(y,y) for y in range(2019, datetime.today().year+1)], default=datetime.now().year,)
    mes_cuota = models.IntegerField('Mes', choices=[(m,m) for m in range(1,13)], default=datetime.now().month,)
    valor = models.DecimalField(verbose_name="Valor Mensual", max_digits=8, decimal_places=2, blank=True, null=True)
    descripcion = models.CharField('Descripcion', max_length=100, blank=True, null=True)
    class Meta:
        ordering = ['ano_cuota', 'mes_cuota']
    def __str__(self):
        return self.socio.apellidos + ', ' + self.socio.nombres + ' ' + str(self.mes_cuota) + '/' + str(self.ano_cuota)
    def pagada(self):
        importe = self.valor
        for pago in self.pagos.all().filter(aprobado=True):
            importe = importe - pago.monto_pagado
        if importe:
            return False, importe
        else:
            return True, 0
    def estado(self):
        if self.pagada()[0]:
            return 'Pagada'
        else:
            for pago in self.pagos.all():
                if pago.aprobado:
                    return 'Falta cancelar una parte'
                else:
                    return 'Aun no se ha aprobado el pago'
            return 'No se ha realizado pago'

class Pago(models.Model):
    cuota = models.ForeignKey(Cuota, on_delete=models.CASCADE, related_name="pagos")
    fecha_pago = models.DateField(verbose_name="Fecha del pago", blank=True, null=True)
    tipo_pago = models.ForeignKey(TipoPago, on_delete=models.CASCADE, related_name="pagos")
    monto_pagado = models.DecimalField(verbose_name="Monto Pagado", max_digits=8, decimal_places=2, blank=True, null=True)
    comprobante = models.FileField('comprobante', upload_to='socios/pagos/', blank=True, null=True)
    aprobado = models.BooleanField(verbose_name="Aprobado", default=False)

#Importamos señanesl
from .signals import nuevo_socio

clubweb/personal/views.py
#Imports de Python
import csv
import calendar
from datetime import date, timedelta, timedelta
#Imports Django
from django.shortcuts import render
from django.http import HttpResponse
from django.db.models import Q
#Imports del proyecto

#Imports App
from .models import Dia
from .models import Empleado, TipoHabilidad, Habilidad
from .models import Sector
from .models import Salario, Comportamiento, Concepto, Detalle
from .forms import EmpleadoSearchForm

# Create your views here.
def personal_menu(request):
    cargados = Salario.objects.order_by('fecha_pago').values('fecha_pago').distinct()
    return render(request, "menu_personal.html", {'cargados': cargados, })

def resumen_empleado(request, id_empleado=None):
    if id_empleado:
        try:
            empleado = Empleado.objects.get(pk=id_empleado)
            return render(request, 'empleado_resumen.html', {'empleado': empleado,})
        except Empleado.DoesNotExist:
            return render(request, 'extras/error.html', {})
    else:
        if request.method == "GET":
            form = EmpleadoSearchForm()
            return render(request, 'extras/generic_form.html', {'form': form, 'titulo': 'Resumen del Empleado', 'boton': 'Buscar'})
        else:
            form = EmpleadoSearchForm(request.POST)
            if form.is_valid():
                try:
                    if form.cleaned_data['num_doc']:
                        empleado = Empleado.objects.get(num_doc=form.cleaned_data['num_doc'])
                    elif form.cleaned_data['num_legajo']:
                        empleado = Empleado.objects.get(num_legajo=form.cleaned_data['num_legajo'])
                    return resumen_empleado(request, empleado.id)  
                except Empleado.DoesNotExist:
                    return render(request, 'extras/error.html', {})
            else:
                return render(request, 'extras/error.html', {})

def buscador(request):
    if request.method == 'POST':
        if 'buscar' in request.POST:
            buscar = request.POST['buscar']
            empleados = Empleado.objects.filter(Q(nombres__icontains=buscar)
                    | Q(apellidos__icontains=buscar)
            )
        return render(request, 'lista_empleados.html', {'empleados': empleados, })
    else:
        return resumen_empleado(request)

def buscar_por_habilidad(request):
    if request.method == "GET":
        tiposhabilidades = TipoHabilidad.objects.all()
        return render(request, 'buscar_por_habilidad.html', {'tiposhabilidades': tiposhabilidades, })
    else:
        #Obtenemos las habilidades seleccionadas
        habilidades = [int(id) for id in request.POST.getlist('habilidad')]
        habilidades = Habilidad.objects.filter(id__in=habilidades)
        #Preparamos la lista a entregar
        empleados = []
        for empleado in Empleado.objects.all().exclude(num_legajo=None):
            empleado.puntaje = 0
            for hab in empleado.habilidades.all():
                if hab.habilidad in habilidades:
                    empleado.puntaje+= hab.nivel
            if empleado.puntaje:
                empleados.append(empleado)
                empleados.sort(key=lambda x: x.puntaje, reverse=True)
        return render(request, 'empleados_por_habilidad.html', {'habilidades_buscadas': habilidades, 'empleados': empleados,})

def ver_turnos(request, id_sector=None):
    lista_sectores = Sector.objects.all()
    if id_sector:
        sectores = Sector.objects.filter(id=id_sector)
    else:
        sectores = lista_sectores
    #Fechamos los dias:
    hoy = type('Generic', (), {'fecha':date.today(), 
                            'numero': date.today().weekday()})
    dias = []
    for dia in Dia.objects.all():
        dia.fecha = hoy.fecha + timedelta(days=(dia.numero - hoy.numero))
        dias.append(dia)#Aca tenemos que asignar la fecha del dia en la semana
    return render(request, 'turnos.html', {'sectores': sectores,
                                            'lista_sectores': lista_sectores,
                                            'horas': range(0,24), 'dias': dias,
                                            'id_sector': id_sector, })

def ver_postulantes(request):
    empleados = Empleado.objects.filter(num_legajo=None)
    return render(request, 'postulantes.html', {'empleados': empleados, })

def ver_salarios(request, fecha):
    salarios = Salario.objects.filter(fecha_pago=fecha)
    return render(request, 'listado_salarios.html', {'salarios': salarios, })

def upload_salarios(request):
    if request.method == 'POST' and 'csvfile' in request.FILES:
        csv_file = request.FILES['csvfile']
        file_data = csv_file.read().decode("utf-8")
        lines = file_data.split("\n")
        salarios = []
        for line in lines:
            line = line.replace('\r', '').split(',')
            try:
                empleado = Empleado.objects.get(num_legajo=line[0])
                salario = Salario()
                salario.empleado = empleado
                salario.begda = line[4]
                salario.endda = line[5]
                salario.importe = line[6]
                salario.fecha_pago = line[7]
                if line[8] == "True":
                    salario.pagado = True
                    salario.pagado_fecha = line[9]
                salarios.append(salario)
            except Empleado.DoesNotExist:
                print('No existe el empleado')
        Salario.objects.bulk_create(salarios)
        return render(request, 'listado_salarios.html', {'salarios': salarios, })
    else:
        cargados = Salario.objects.order_by('fecha_pago').values('fecha_pago').distinct()
        return render(request, 'upload_salarios.html', {'cargados': cargados, })

def excel_ejemplo_simple(request):
    response = HttpResponse(content_type='text/csv')
    fecha = date.today()
    begda = date(fecha.year, fecha.month, 1)
    endda = date(begda.year, begda.month, calendar.monthrange(begda.year,begda.month)[1])
    next_month = (fecha.replace(day=1) + timedelta(days=32)).replace(day=1)
    response['Content-Disposition'] = 'attachment; filename="salario'+str(fecha)+'.csv"'
    writer = csv.writer(response)
    writer.writerow(['Archivo Simple'])
    writer.writerow(['Num Legajo', 'Num Doc', 'Apellidos', 'Nombre', 'Inicio Periodo', 'Fin Periodo', 'Importe', 'Fecha de Cobro', 'Pagado (False/True)',  'Fecha de Pago'])
    for empleado in Empleado.objects.exclude(num_legajo=None):
        writer.writerow([empleado.num_legajo, empleado.num_doc, 
            empleado.apellidos, empleado.nombres, 
            begda, endda, 0, 
            date(next_month.year, next_month.month, 10), 
            False, date(9999, 12, 31)])
    return response


def excel_ejemplo_avanzado(request):


    response = HttpResponse(content_type='text/csv')
    fecha = date.today()
    begda = date(fecha.year, fecha.month, 1)
    endda = date(begda.year, begda.month, calendar.monthrange(begda.year,begda.month)[1])
    next_month = (fecha.replace(day=1) + timedelta(days=32)).replace(day=1)
    response['Content-Disposition'] = 'attachment; filename="salario'+str(fecha)+'.csv"'
    writer = csv.writer(response)
    writer.writerow(['Archivo Simple'])
    writer.writerow(['Num Legajo', 'Num Doc', 'Apellidos', 'Nombre', 'Inicio Periodo', 'Fin Periodo', 'Importe', 'Fecha de Cobro', 'Pagado (False/True)',  'Fecha de Pago'])
    for empleado in Empleado.objects.exclude(num_legajo=None):
        writer.writerow([empleado.num_legajo, empleado.num_doc, 
            empleado.apellidos, empleado.nombres, 
            begda, endda, 0, 
            date(next_month.year, next_month.month, 10), 
            False, date(9999, 12, 31)])
    return response

clubweb/personal/templates/base_personal.html
{% extends 'base/base.html' %}

{% load static %}

{% block custom_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/personal.css' %}" />
{% endblock %}

{% block content %}

{% endblock %}

{% block custom_script %}

{% endblock %}

clubweb/personal/templates/buscar_por_habilidad.html
{% extends 'base_personal.html' %}


{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">        
                    <h1>Buscar empleado por Habilidades:</h1>
                    <div class="col-md-12">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="listado">
                                        {% for tipo in tiposhabilidades %}
                                            {% if forloop.first %}
                                                <tr>
                                                    <th>Tipo</th>
                                                    <th>Nombre</th>
                                                    <th>Marcar</th>
                                                </tr>
                                            {% endif %}
                                            {% for habilidad in tipo.agrupadas.all %}
                                                <tr>
                                                    <td>{{tipo.nombre}}</td>
                                                    <td>{{habilidad.nombre}}</td>
                                                    <td><input type="checkbox" name="habilidad" value="{{habilidad.id}}"></td>
                                                </tr>
                                            {% endfor %}
                                        {% endfor %}
                                    </table>
                                </div>
                            </div>
                            <br>
                            <div class="row spacer">
                                <div class="col-md-5"></div>
                                <div class="col-md-2">
                                    <button type="submit" class="btn btn-block btn-primary">Buscar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

clubweb/personal/templates/empleado_resumen.html
{% extends 'base_personal.html' %}

{% block content %}
    <div class="empleado container">
        <div class="row">
            <div class="row">
                <h2>
                    {{empleado.apellidos}}, {{empleado.nombres}}
                    <a target="_blank" href="/admin/personal/empleado/{{empleado.id}}">
                        <img src="/static/admin/img/icon-changelink.svg" alt="Modificar">
                    </a>
                </h2>
            </div>
            <div class="row">
                <div class="col-md-9">
                    {% if empleado.foto %}
                        <div class="col-md-6">
                            <img class="retrato" src="{{empleado.foto.url}}" alt="(foto)">
                        </div>
                    {% endif %}
                    <div class="col-md-6">
                        <h3><b>Datos Laborales</b></h3>
                        {% if empleado.num_legajo %}
                            <p><b>N° Legajo:</b> {{empleado.num_legajo}}</p>
                        {% else %}
                            <p><b>Postulante</b></p>
                        {% endif %}
                        {% if empleado.contrato_actual %}
                            <p>
                                <b>Cargo Actual:</b> {{empleado.contrato_actual.cargo.nombre}}
                                {% if empleado.contrato_actual.subcargo %}
                                    - {{empleado.contrato_actual.subcargo}}
                                {% endif %}
                            </p>
                            {% if empleado.contrato_actual.unidad %}
                                <p>
                                    <b>Area:</b> {{empleado.contrato_actual.unidad.nombre}}{{empleado.contrato_actual.sector.nombre}}
                                    <a target="_blank" href="/admin/organigrama/unidad/{{empleado.contrato_actual.unidad.id}}">
                                        <img src="/static/admin/img/icon-changelink.svg" alt="Modificar">
                                    </a>
                                </p>
                            {% endif %}
                            <p><b>Contratacion:</b> {{empleado.contrato_actual.begda}} - Actualidad</p>
                            {% if empleado.contratos_previo %}
                            <div class="popup-overlay"></div>
                            <div class="popup">
                                <a>Ver Historial</a>
                                <div class="popuptext">
                                    <h2>Historial</h2>
                                    <ul>
                                        {% for contrato in empleado.contratos.all %}
                                            <li>
                                                {{contrato.cargo.nombre}} en <b>{{contrato.unidad.nombre}}</b>
                                                desde {{contrato.begda}} hasta 
                                                {% if contrato.endda|date:"dmY" == '31129999' %}
                                                    la actualidad.
                                                {% else %}
                                                    {{contrato.endda}}
                                                {% endif %}
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                            {% endif %}
                        {% endif %}
                        
                        <h3><b>Datos Personales</b></h3>
                        {% if empleado.num_doc %}<p><b>Numero de Documento:</b> {{empleado.num_doc}}</p>{% endif %}
                        {% if empleado.fecha_nacimiento %}<p><b>Fecha De Nacimiento:</b> {{empleado.fecha_nacimiento}}</p>{% endif %}
                        {% if empleado.estado_civil %}<p><b>Estado Civil:</b> {{empleado.get_estado_civil_display}}</p>{% endif %}
                        {% if empleado.domicilio %}<p><b>Domicilio:</b>{{empleado.domicilio}}</p>{%endif%}
                        {% if empleado.telefono %}<p><b>Telefono:</b>{{empleado.telefono}}</p>{%endif%}
                        {% if empleado.email %}<p><b>Email: </b><a href="mailto:{{empleado.email}}" target="_blank">{{empleado.email}}</a></p>{%endif%}
                    </div>
                    <hr>
                    {% if empleado.escolaridad.all %}
                        <div class="col-md-12">
                            <h2>Escolaridad</h2>
                            {% for escolar in empleado.escolaridad.all %}
                                <div class="col-md-6">
                                    <p><b>Nivel:</b>
                                        {{escolar.get_nivel_display}}
                                        {% if escolar.terminado %}
                                            <b> (Finalizado)</b>
                                        {% else %}
                                            <b> (En proceso)</b>
                                        {% endif %}
                                    </p>
                                    <p><b>Titulo:</b>{{escolar.titulo}}</p>
                                    <p><b>Establecimiento:</b>{{escolar.establecimiento}}</p>
                                    <p><b>Fechas:</b>
                                        {{escolar.begda}}
                                        {% if escolar.terminado %}
                                            a {{escolar.endda}}
                                        {% endif %}
                                    </p>
                                </div>
                            {% endfor %}
                        </div>
                        <hr>
                    {% endif %}
                    {% if empleado.documentos.all %}
                        <div class="col-md-12">
                            <h2>Documentacion</h2>
                            <br>
                            {% for documento in empleado.documentos.all %}
                                <div class="col-md-4">
                                    <p>
                                        <b>{{documento.tipo.nombre}}</b>
                                        <a href="{{documento.archivo.url}}" target="_blank">(Ver)</a>
                                    </p>
                                    <p>{{documento.descripcion}}</p>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="col-md-3">
                    <h2><b>Habilidades:</b></h2>
                    <ul>
                        {% for tipo in empleado.tipo_habilidades %}
                            <li><p>{{tipo.nombre}}:</p>
                                <ul>
                                    {% for hab in empleado.habilidades.all %}
                                        {% if tipo == hab.habilidad.tipo %}
                                            <li>{{hab.habilidad.nombre}}: {{hab.get_nivel_display}}</li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </li>
                            <br>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

clubweb/personal/templates/empleados_por_habilidad.html
{% extends 'base_personal.html' %}


{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">        
                    <div class="col-md-12">
                        <h1>Empleados con este Perfil:</h1>
                        {% for empleado in empleados %}
                            <div class="col-md-6">
                                <h3>
                                    {{empleado.apellidos}}, {{empleado.nombres}}
                                    <a target="_blank" href="/admin/personal/empleado/{{empleado.id}}">
                                        <img src="/static/admin/img/icon-changelink.svg" alt="Modificar">
                                    </a>
                                </h3>
                                <p>
                                    <b>Puntaje:</b>{{empleado.puntaje}}
                                     <a target="_blank" href="/personal/buscar/{{empleado.id}}">(Ver Resumen)</a>
                                </p>
                                <table class="turnero">
                                    <tr>
                                        <th>Habilidad</th>
                                        <th>Nivel</th>
                                    </tr>
                                    {% with empleado.habilidades.all as habilidades_adquiridas %}
                                        {% for habilidad in habilidades_buscadas %}
                                            <tr>
                                                <td>{{habilidad.nombre}}</td>
                                                <td>
                                                    {% for habilidad_adquirida in habilidades_adquiridas %}
                                                        {% if habilidad_adquirida.habilidad ==  habilidad %}
                                                            {{habilidad_adquirida.get_nivel_display}} ({{habilidad_adquirida.nivel}})
                                                        {% endif %}
                                                    {% endfor %}
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    {% endwith %}
                                </table>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

clubweb/personal/templates/info_derecha_personal.html
{% block content %}
    <p style="margin-bottom:-10px;">Buscar Empleado</p>
    {% include 'extras/buscador.html' %}
    <!-- Podriamos Mostra Salarios Procesados -->
    <h4>Periodos Cargados:</h4>
    <ul>
        {% for cargado in cargados %}
            <li>
                <a href="/personal/salarios/{{cargado.fecha_pago|date:"Y-m-d"}}">
                    {{cargado.fecha_pago}}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}